# Generated by Django 5.0.14 on 2025-11-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_behavior_score",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="user",
            name="ai_processing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ai_risk_level",
            field=models.CharField(default="low", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="ai_user_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]