# Generated by Django 5.1.7 on 2025-10-30 08:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ministry_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "name_sw",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name (Swahili)",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number with country code (e.g., +254712345678).",
                                regex="^\\+?\\d{10,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Optional: Official ministry website",
                        null=True,
                        validators=[
                            django.core.validators.URLValidator(
                                message="Enter a valid website URL."
                            )
                        ],
                    ),
                ),
                ("description", models.TextField()),
                (
                    "description_sw",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description (Swahili)"
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("kpi_resolved", models.IntegerField(default=0)),
                ("kpi_pending", models.IntegerField(default=0)),
                ("kpi_under_review", models.IntegerField(default=0)),
                ("kpi_rejected", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_ministry",
                        to="users.governmentadmin",
                        verbose_name="Government Admin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ministry",
                "verbose_name_plural": "Ministries",
                "ordering": ["name"],
            },
        ),
    ]
