# Generated by Django 5.1.6 on 2025-02-08 15:59

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with country code (e.g., +254712345678).', regex='^\\+?\\d{10,15}$')])),
                ('website', models.URLField(blank=True, help_text='Optional: Official ministry website', null=True, validators=[django.core.validators.URLValidator(message='Enter a valid website URL.')])),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('kpi_resolved', models.IntegerField(default=0)),
                ('kpi_pending', models.IntegerField(default=0)),
                ('kpi_under_review', models.IntegerField(default=0)),
                ('kpi_rejected', models.IntegerField(default=0)),
            ],
        ),
    ]
