# Generated by Django 5.1.6 on 2025-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='password',
            field=models.CharField(default='ministry1', max_length=255),
            preserve_default=False,
        ),
    ]
