# Generated by Django 5.1.7 on 2025-10-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("report_view", "Report Viewed"),
                            ("report_update", "Report Updated"),
                            ("report_assign", "Report Assigned"),
                            ("ministry_approve", "Ministry Approved"),
                            ("ministry_reject", "Ministry Rejected"),
                            ("alert_dismiss", "Alert Dismissed"),
                            ("export_data", "Data Exported"),
                            ("widget_configure", "Widget Configured"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Dashboard Activities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DashboardAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("show_to_all", models.BooleanField(default=False)),
                ("target_roles", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("total_reports", "Total Reports"),
                            ("pending_reports", "Pending Reports"),
                            ("resolved_reports", "Resolved Reports"),
                            ("active_ministries", "Active Ministries"),
                            ("active_users", "Active Users"),
                            ("reports_by_category", "Reports by Category"),
                            ("reports_by_priority", "Reports by Priority"),
                            ("avg_resolution_time", "Average Resolution Time"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.JSONField(default=dict)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("stats_card", "Statistics Card"),
                            ("chart", "Chart"),
                            ("table", "Data Table"),
                            ("map", "Map View"),
                            ("timeline", "Timeline"),
                            ("activity_feed", "Activity Feed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("government_admin", "Government Admin"),
                            ("ministry", "Ministry"),
                            ("citizen", "Citizen"),
                            ("all", "All Users"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["role", "position"],
            },
        ),
        migrations.CreateModel(
            name="SystemHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("degraded", "Degraded Performance"),
                            ("partial_outage", "Partial Outage"),
                            ("major_outage", "Major Outage"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "uptime_percentage",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("last_check", models.DateTimeField(auto_now=True)),
                ("details", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["component"],
            },
        ),
    ]
