# Generated by Django 5.0.14 on 2025-11-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="ai_confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_hotspot_prediction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_predicted_priority",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_processing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_recommendations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="report",
            name="ai_similar_reports",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
