# Generated by Django 5.1.7 on 2025-03-13 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('fire_department', 'Fire Department'), ('medical_services', 'Medical Services'), ('infrastructure', 'Infrastructure Maintenance'), ('environmental', 'Environmental Management')], max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DisasterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pothole', 'Pothole'), ('road_damage', 'Road Damage'), ('fire', 'Fire'), ('flood', 'Flood'), ('earthquake', 'Earthquake'), ('medical', 'Medical Emergency'), ('building_collapse', 'Building Collapse'), ('power_outage', 'Power Outage'), ('theft', 'Theft/Robbery'), ('other', 'Other')], max_length=50)),
                ('other_category', models.CharField(blank=True, help_text="Specify the issue if 'Other' is selected.", max_length=255, null=True)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='disaster_reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disaster_reporting.disasteragency')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'citizen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
