# Generated by Django 5.0.14 on 2025-11-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disaster_reporting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disasterreport",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="disasterreport",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="disasterreport",
            name="tracking_code",
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="DisasterMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("file", models.FileField(upload_to="disaster_reports/media/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="disaster_reporting.disasterreport",
                    ),
                ),
            ],
        ),
    ]
