# Generated by Django 5.1.7 on 2025-03-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterreport',
            name='other_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
