# Generated by Django 5.1.7 on 2025-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_reporting', '0002_alter_disasterreport_other_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterreport',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disasterreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('invalid', 'Invalid')], default='pending', max_length=20),
        ),
    ]
