# Generated by Django 5.1.7 on 2025-03-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_reporting', '0003_disasterreport_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasteragency',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disasteragency',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
